package com.example.dao.mapper;


import com.example.dao.entity.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	int countByExample(User example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	int deleteByExample(User example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	int deleteByPrimaryKey(Long UserId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	int insert(Map<String, Object> params);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	int insertSelective(Map<String, Object> params);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	List<User> selectByExample(User example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	User selectByPrimaryKey(Long UserId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	int updateByExampleSelective(@Param("record") User record, @Param("example") User example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	int updateByExample(@Param("record") User record, @Param("example") User example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	User getUserByUserName(String userName, String password);



}