package com.example.dao.entity;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.USER_ID
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.USER_NAME
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.PASSWORD
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.NAME
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.PHONE_NUMBER
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	private String phoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.CREATE_TIME
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.CREATOR
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	private Long creator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.WHO_MODIFY
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	private Long whoModify;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.MODIFY_TIME
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.VERSION
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	private String version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.FLAT_ID
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	private String flatId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.PASSWORD_CHANGED
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	private String passwordChanged;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.PASSWORD_CHANGE_TIME
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	private Date passwordChangeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.ONJOB
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	private Integer onjob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.ISFREEZ
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	private Integer isfreez;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.ISVALID
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	private Integer isvalid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.USER_ID
	 * @return  the value of user.USER_ID
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.USER_ID
	 * @param userId  the value for user.USER_ID
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.USER_NAME
	 * @return  the value of user.USER_NAME
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.USER_NAME
	 * @param userName  the value for user.USER_NAME
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.PASSWORD
	 * @return  the value of user.PASSWORD
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.PASSWORD
	 * @param password  the value for user.PASSWORD
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.NAME
	 * @return  the value of user.NAME
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.NAME
	 * @param name  the value for user.NAME
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.PHONE_NUMBER
	 * @return  the value of user.PHONE_NUMBER
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.PHONE_NUMBER
	 * @param phoneNumber  the value for user.PHONE_NUMBER
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.CREATE_TIME
	 * @return  the value of user.CREATE_TIME
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.CREATE_TIME
	 * @param createTime  the value for user.CREATE_TIME
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.CREATOR
	 * @return  the value of user.CREATOR
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public Long getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.CREATOR
	 * @param creator  the value for user.CREATOR
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public void setCreator(Long creator) {
		this.creator = creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.WHO_MODIFY
	 * @return  the value of user.WHO_MODIFY
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public Long getWhoModify() {
		return whoModify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.WHO_MODIFY
	 * @param whoModify  the value for user.WHO_MODIFY
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public void setWhoModify(Long whoModify) {
		this.whoModify = whoModify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.MODIFY_TIME
	 * @return  the value of user.MODIFY_TIME
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.MODIFY_TIME
	 * @param modifyTime  the value for user.MODIFY_TIME
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.VERSION
	 * @return  the value of user.VERSION
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.VERSION
	 * @param version  the value for user.VERSION
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public void setVersion(String version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.FLAT_ID
	 * @return  the value of user.FLAT_ID
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public String getFlatId() {
		return flatId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.FLAT_ID
	 * @param flatId  the value for user.FLAT_ID
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public void setFlatId(String flatId) {
		this.flatId = flatId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.PASSWORD_CHANGED
	 * @return  the value of user.PASSWORD_CHANGED
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public String getPasswordChanged() {
		return passwordChanged;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.PASSWORD_CHANGED
	 * @param passwordChanged  the value for user.PASSWORD_CHANGED
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public void setPasswordChanged(String passwordChanged) {
		this.passwordChanged = passwordChanged;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.PASSWORD_CHANGE_TIME
	 * @return  the value of user.PASSWORD_CHANGE_TIME
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public Date getPasswordChangeTime() {
		return passwordChangeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.PASSWORD_CHANGE_TIME
	 * @param passwordChangeTime  the value for user.PASSWORD_CHANGE_TIME
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public void setPasswordChangeTime(Date passwordChangeTime) {
		this.passwordChangeTime = passwordChangeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.ONJOB
	 * @return  the value of user.ONJOB
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public Integer getOnjob() {
		return onjob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.ONJOB
	 * @param onjob  the value for user.ONJOB
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public void setOnjob(Integer onjob) {
		this.onjob = onjob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.ISFREEZ
	 * @return  the value of user.ISFREEZ
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public Integer getIsfreez() {
		return isfreez;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.ISFREEZ
	 * @param isfreez  the value for user.ISFREEZ
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public void setIsfreez(Integer isfreez) {
		this.isfreez = isfreez;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.ISVALID
	 * @return  the value of user.ISVALID
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public Integer getIsvalid() {
		return isvalid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.ISVALID
	 * @param isvalid  the value for user.ISVALID
	 * @mbggenerated  Tue Jul 25 14:04:02 CST 2017
	 */
	public void setIsvalid(Integer isvalid) {
		this.isvalid = isvalid;
	}
}